version: '3.8'

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.2
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1514:1514/tcp"
      - "1515:1515/tcp"
      - "55000:55000/tcp"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USER=admin
      - INDEXER_PASSWORD=SecretPassword123!
    volumes:
      - wazuh_manager_data:/var/ossec/data

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.7.2
    hostname: wazuh.indexer
    restart: always
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - wazuh_indexer_data:/var/lib/wazuh-indexer

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.2
    hostname: wazuh.dashboard
    restart: always
    ports:
      - "443:5601/tcp"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - WAZUH_MANAGER_URL=https://wazuh.manager:55000
    depends_on:
      - wazuh.indexer
      - wazuh.manager

volumes:
  wazuh_manager_data:
  wazuh_indexer_data:
